# Generated by Django 4.1.3 on 2022-12-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_balance_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_per',
            field=models.IntegerField(choices=[(10, 10), (15, 15), (25, 25), (50, 50), (75, 75), (100, 100)], default=10, verbose_name='Balance percent per trade'),
        ),
    ]
