# Generated by Django 4.1.4 on 2022-12-22 07:50

import Users.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_alter_user_balance_per"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "base_manager_name": "prefetch_manager",
                "ordering": ["first_name", "last_name"],
                "verbose_name": "user",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", Users.models.UserManager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="email_verify",
            new_name="verified",
        ),
        migrations.AddField(
            model_name="trader",
            name="admin_leverage",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Admin default leverage"
            ),
        ),
        migrations.AddField(
            model_name="trader",
            name="api_key",
            field=models.CharField(blank=True, max_length=265, verbose_name="api_key"),
        ),
        migrations.AddField(
            model_name="trader",
            name="api_secret",
            field=models.CharField(
                blank=True, max_length=265, verbose_name="api_secret"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
